name: Weekly Mortgage Rate Prediction

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs at 00:00 on Monday
  workflow_dispatch:  # Allows manual trigger

jobs:
  predict_rates:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run prediction pipeline
      env:
        FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
      run: |
        python scripts/run_mortgage_prediction.py
        
    - name: Generate email report
      run: |
        python scripts/generate_email_report.py
        
    - name: Send email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: Weekly Mortgage Rate Prediction Report
        body: file://email_report.html
        html_body: file://email_report.html
        to: ${{ secrets.EMAIL_RECIPIENT }}
        from: GitHub Actions
        attachments: |
          results/evaluation_metrics.csv
          results/plots/actual_vs_predicted.png
          results/plots/residuals.png
          results/plots/feature_importance.png