name: Weekly Mortgage Rate Prediction

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs at 00:00 on Monday
  workflow_dispatch:  # Allows manual trigger

jobs:
  predict_rates:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run prediction pipeline
      env:
        FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
      run: |
        python scripts/run_mortgage_prediction.py
        
    - name: Generate report
      run: |
        python scripts/generate_email_report.py
        
    - name: Upload report and plots
      uses: actions/upload-artifact@v4
      with:
        name: weekly-mortgage-report
        path: |
          email_report.html
          results/evaluation_metrics.csv
          results/plots/*.png

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: mortgage-report-${{ github.run_number }}
        name: "Weekly Mortgage Rate Report #${{ github.run_number }}"
        body_path: email_report.html
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          results/evaluation_metrics.csv
          results/plots/*.png
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}