name: Weekly Mortgage Rate Prediction

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs at 00:00 on Monday
  workflow_dispatch:  # Allows manual trigger
permissions:
  contents: write

jobs:
  predict_rates:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run prediction pipeline
      env:
        FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
      run: |
        python scripts/run_mortgage_prediction.py
        
    - name: Generate report
      run: |
        python scripts/generate_report.py
        
    - name: Upload report and plots
      uses: actions/upload-artifact@v4
      with:
        name: weekly-mortgage-report
        path: |
          release_report.md
          results/evaluation_metrics.csv
          results/plots/*.png

    - name: Set report date
      run: echo "REPORT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Create release with report
      uses: softprops/action-gh-release@v1
      with:
        tag_name: mortgage-report-${{ env.REPORT_DATE }}
        name: "Mortgage Rate Report – ${{ env.REPORT_DATE }}"
        body_path: release_report.md
        files: |
          results/evaluation_metrics.csv
          results/plots/*.png
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}