name: Weekly Mortgage Rate Prediction

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs at 00:00 on Monday
  workflow_dispatch:  # Allows manual trigger
permissions:
  contents: write

jobs:
  predict_and_report:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run prediction pipeline
      env:
        FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
      run: |
        python scripts/run_mortgage_prediction.py

    - name: Set report date
      run: echo "REPORT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Create Release Directory
      run: |
        mkdir -p release_assets
        cp -r results/plots release_assets/
        cp results/evaluation_metrics.csv release_assets/

    - name: Generate report
      env:
        REPORT_DATE: ${{ env.REPORT_DATE }}
      run: |
        python scripts/generate_report.py

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: mortgage-report-${{ env.REPORT_DATE }}
        name: "Mortgage Rate Report – ${{ env.REPORT_DATE }}"
        body_path: release_report.md
        files: |
          release_assets/plots/*
          release_assets/evaluation_metrics.csv
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}